export enum Env {
  DB_USERNAME = 'DB_USERNAME',
  DB_PASSWORD = 'DB_PASSWORD',

  JWT_SECRET = 'JWT_SECRET',

  EMAIL_USER = 'EMAIL_USER',
  EMAIL_CLIENT_ID = 'EMAIL_CLIENT_ID',
  EMAIL_CLIENT_SECRET = 'EMAIL_CLIENT_SECRET',
  EMAIL_REFRESH_TOKEN = 'EMAIL_REFRESH_TOKEN',

  MESSAGE_ENCRYPTION_KEY = 'MESSAGE_ENCRYPTION_KEY',
}
